version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance

issues:
  exclude-dirs:
    - gen
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
